import React, { useState } from 'react';

export default function PackingSlipPreview({ invoice, onNavigate }) {
  const [tasks, setTasks] = useState([
    {
      id: 1,
      name: 'Verify received items in warehouse',
      assigned: 'Warehouse Manager',
      status: 'Pending',
      dueDate: '2026-04-30',
    },
    {
      id: 2,
      name: 'Prepare packing slip',
      assigned: 'Logistics Team',
      status: 'In Progress',
      dueDate: '2026-04-30',
    },
    {
      id: 3,
      name: 'Schedule delivery',
      assigned: 'Delivery Coordinator',
      status: 'Pending',
      dueDate: '2026-05-01',
    },
    {
      id: 4,
      name: 'Notify sales team about new arrivals',
      assigned: 'Sales Manager',
      status: 'Pending',
      dueDate: '2026-04-30',
    },
  ]);

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="container mx-auto px-6 py-12">
      <div className="mb-8">
        <button
          onClick={() => onNavigate('dashboard')}
          className="text-blue-600 hover:text-blue-800 font-semibold mb-4"
        >
          ← Back to Dashboard
        </button>
        <h2 className="text-3xl font-bold text-gray-800">Packing Slip Preview</h2>
        <p className="text-gray-600 mt-2">Invoice ID: {invoice.id}</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Packing Slip */}
        <div className="lg:col-span-2">
          <div className="bg-white rounded-lg shadow-lg p-8 border-2 border-gray-200">
            {/* Header */}
            <div className="border-b-2 border-gray-300 pb-6 mb-6">
              <div className="flex justify-between items-start mb-4">
                <div>
                  <h1 className="text-4xl font-bold text-gray-800">PACKING SLIP</h1>
                  <p className="text-gray-600 text-sm">Makro Food Distribution</p>
                </div>
                <div className="text-right">
                  <p className="text-gray-600 text-sm">Invoice ID: <span className="font-bold">{invoice.id}</span></p>
                  <p className="text-gray-600 text-sm">Date: <span className="font-bold">{invoice.date}</span></p>
                </div>
              </div>
            </div>

            {/* Vendor Info */}
            <div className="mb-8">
              <h3 className="text-sm font-bold text-gray-700 uppercase mb-2">From Vendor</h3>
              <p className="text-lg font-semibold text-gray-800">{invoice.vendor}</p>
              <p className="text-gray-600 text-sm">Date Received: {invoice.date}</p>
            </div>

            {/* Items Table */}
            <div className="mb-8">
              <h3 className="text-sm font-bold text-gray-700 uppercase mb-3">Items</h3>
              <table className="w-full border-collapse border-2 border-gray-300">
                <thead>
                  <tr className="bg-gray-200">
                    <th className="border border-gray-300 px-4 py-2 text-left text-sm font-bold text-gray-800">Product Name</th>
                    <th className="border border-gray-300 px-4 py-2 text-center text-sm font-bold text-gray-800">Quantity</th>
                    <th className="border border-gray-300 px-4 py-2 text-center text-sm font-bold text-gray-800">Cases</th>
                    <th className="border border-gray-300 px-4 py-2 text-center text-sm font-bold text-gray-800">Unit</th>
                  </tr>
                </thead>
                <tbody>
                  {invoice.items.map((item, index) => (
                    <tr key={index} className="border-b border-gray-300">
                      <td className="border border-gray-300 px-4 py-2 text-sm text-gray-700">{item.name}</td>
                      <td className="border border-gray-300 px-4 py-2 text-center text-sm text-gray-700">{item.quantity}</td>
                      <td className="border border-gray-300 px-4 py-2 text-center text-sm text-gray-700">{item.cases}</td>
                      <td className="border border-gray-300 px-4 py-2 text-center text-sm text-gray-700">{item.unit}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <p className="text-sm text-gray-600 mt-2">Total Items: {invoice.items.length} | Total Quantity: {invoice.items.reduce((sum, item) => sum + parseInt(item.quantity || 0), 0)}</p>
            </div>

            {/* Notes */}
            <div className="bg-blue-50 border-l-4 border-blue-500 p-4 mb-8">
              <p className="text-sm text-gray-700"><strong>Note:</strong> This packing slip contains product names and quantities only. Prices are excluded for warehouse operations.</p>
            </div>

            {/* Footer */}
            <div className="text-center text-xs text-gray-500 border-t pt-4">
              <p>Generated by Makro AI • Project Management Mode</p>
              <p className="mt-1">Professional packing slip for warehouse and delivery teams</p>
            </div>
          </div>
        </div>

        {/* Actions & Status */}
        <div className="space-y-6">
          {/* Quick Actions */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-lg font-bold text-gray-800 mb-4">Actions</h3>
            <div className="space-y-3">
              <button
                onClick={handlePrint}
                className="w-full bg-blue-600 hover:bg-blue-700 text-white font-semibold py-2 px-4 rounded transition"
              >
                🖨️ Print Packing Slip
              </button>
              <button
                onClick={() => onNavigate('tasks')}
                className="w-full bg-purple-600 hover:bg-purple-700 text-white font-semibold py-2 px-4 rounded transition"
              >
                📋 Manage Tasks
              </button>
              <button
                onClick={() => onNavigate('workflow')}
                className="w-full bg-green-600 hover:bg-green-700 text-white font-semibold py-2 px-4 rounded transition"
              >
                📊 View Workflow
              </button>
            </div>
          </div>

          {/* Auto-Generated Tasks */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-lg font-bold text-gray-800 mb-4">Auto-Generated Tasks</h3>
            <div className="space-y-3">
              {tasks.map((task) => {
                const statusColor = {
                  'Pending': 'bg-yellow-100 text-yellow-800',
                  'In Progress': 'bg-blue-100 text-blue-800',
                  'Done': 'bg-green-100 text-green-800',
                }[task.status];

                return (
                  <div key={task.id} className="p-3 border border-gray-200 rounded">
                    <p className="text-sm font-semibold text-gray-800">{task.name}</p>
                    <p className="text-xs text-gray-600 mt-1">👤 {task.assigned}</p>
                    <div className="flex justify-between items-center mt-2">
                      <span className={`text-xs px-2 py-1 rounded ${statusColor}`}>{task.status}</span>
                      <span className="text-xs text-gray-500">📅 {task.dueDate}</span>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>

          {/* Invoice Status */}
          <div className="bg-white rounded-lg shadow-lg p-6">
            <h3 className="text-lg font-bold text-gray-800 mb-4">Invoice Status</h3>
            <div className="bg-gray-100 rounded-lg p-4">
              <p className="text-sm text-gray-700 mb-2">Current Stage:</p>
              <p className="text-xl font-bold text-blue-600">{invoice.status}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
